### ISSUE TITLE
French wording can be improved

### ISSUE THREAD

**Issue by pylapp** [Horizontal-org/Tella-iOS#167]
## Expected behavior

All texts must be translated in french

## Actual behavior

Some textes are still in english

## Steps to reproduce the problem

Just run the app (App Store v1.9.0 (75))

## Additional information

See pull request https://github.com/Horizontal-org/Tella-iOS/pull/169

**Comment by carohadad** [comment]
Thank you @pylapp !

Tella iOS will be 100% translated to French in the next release thanks to you!

<img width="617" alt="Screenshot 2024-08-05 at 1 11 08 PM" src="https://github.com/user-attachments/assets/0477671c-7a8f-458f-baa3-b4a8d639da2d">


I will update the README soon so new contributors can join our translation management platform. More guidance on how do we manage translations, here: https://tella-app.org/translating-tella
