### ISSUE TITLE
Add audio recorder

### ISSUE THREAD

**Issue by raphmim** [Horizontal-org/Tella-iOS#22]
Users should be able to record audio directly from Tella, and for the audio recordings to be automatically saved into the Gallery.

**Comment by pastre** [comment]
Hi! Can I make this, as a part of Hacktoberfest?

**Comment by Raph33** [comment]
Yes @pastre, please go ahead :)

**Comment by pastre** [comment]
Sorry for the long pull request, this is a new feature, after all :)

**Comment by Raph33** [comment]
Yes it is, it makes sense that it's a long PR :) We'll be compiling a new version with these changes and testing it later this week.
