### ISSUE TITLE
In grid view, show thumbnails of photos and videos

### ISSUE THREAD

**Issue by Raph33** [Horizontal-org/Tella-iOS#29]
When the Gallery is in Grid view, it should display a thumbnail of photos and videos so that the user can identify files without having to open them individually.

**Comment by Thisura98** [comment]
Hi @Raph33, hope you're doing alright.

Is it okay if I work on this as part of Hacktoberfest?

**Comment by Raph33** [comment]
Absolutely @Thisura98, go ahead :)

**Comment by Thisura98** [comment]
Hello again @Raph33 , apologies for the static delay and hope you are safe.

I was able to add a GridView that supports Images for now. Would you be able to take a look?

**Comment by Raph33** [comment]
Thank you @Thisura98! Absolutely, we'll take a look in the coming days.
cc- @ahlem-jarrar
