### ISSUE TITLE
Remove "Collect" button from homescreen

### ISSUE THREAD

**Issue by Raph33** [Horizontal-org/Tella-iOS#30]
V1.0 of the app will not include support for data-collection. The "Collect" button on the homescreen should be removed.

**Comment by subdan** [comment]
I will make it as a part of Hacktoberfest 2020. I will make PR on October, 1.

**Comment by subdan** [comment]
Can I remove `CollectView` struct and `MainViewEnum.COLLECT` enum case?

**Comment by tomislavr** [comment]
Yes, you can.
