### ISSUE TITLE
Video continues to play when you go to background

### ISSUE THREAD

**Issue by Jadekin** [Horizontal-org/Tella-iOS#48]
## Expected behavior
Video stops when you go to background and doesn't play anything when you are opening the app again. 

## Actual behavior
Video still plays and after you come back from background, you can hear the audio while tapping your PIN.

## Steps to reproduce the problem

1. Homescreen
2. Tap Video icon.
3. Select a video from the list
4. Tap play.
5. Change to another app
6. Go back to the app

## Additional information

It is related to this other bug https://github.com/Horizontal-org/Tella-iOS/issues/47, must be a session issue.

**Comment by carohadad** [comment]
hey @Jadekin !! I'm so sorry for not seeing your message on time. I tested this 2 bugs on my phone and it should be fixed now. Could you please update and take a look again ?

If it's still not working properly, can you please include what device you are using ?

Thank you!

**Comment by Jadekin** [comment]
Cool thanks! I just use it now, and yes! they are fixed!! Thanks so much! Closing with a comment!
